// Replay.tsx - a recorded session, played back into the same twin.
//
// The takes bundled here are the repository's own samples: choreographed and
// synthetic, generated by a script that ships beside them, using the real
// take format and the real column layout. A take recorded by the device drops
// in unchanged, which is the whole point of not inventing a format.
import React, { useMemo, useRef, useState } from 'react';
import { View, ScrollView, Pressable, StyleSheet, PanResponder } from 'react-native';
import { Twin } from '../twin/Twin';
import { Card, Label, Mono, UIText, Hairline, Segmented } from '../ui/primitives';
import { Sparkline } from '../ui/Meters';
import { C, S, R, FINGERS } from '../ui/tokens';
import { useSession } from '../data/session';
import { bundledTakes } from '../data/takes';

const SPEEDS = [
  { key: '0.5', label: '0.5×' },
  { key: '1', label: '1×' },
  { key: '2', label: '2×' },
] as const;

export function Replay({ stageHeight }: { stageHeight: number }) {
  const session = useSession();
  const takes = useMemo(bundledTakes, []);
  const [speed, setSpeed] = useState<(typeof SPEEDS)[number]['key']>('1');
  const play = session.play;
  const barW = useRef(1);

  // the take's own effort trace, sampled thin enough to read as a shape
  const trace = useMemo(() => {
    if (!play) return [];
    const n = 56;
    const step = Math.max(1, Math.floor(play.take.frames.length / n));
    return play.take.frames.filter((_, i) => i % step === 0).map((f) => Math.max(0, f.emg));
  }, [play?.take.id]);

  const scrub = useMemo(
    () =>
      PanResponder.create({
        onStartShouldSetPanResponder: () => true,
        onMoveShouldSetPanResponder: () => true,
        onPanResponderGrant: (e) => seekAt(e.nativeEvent.locationX),
        onPanResponderMove: (e) => seekAt(e.nativeEvent.locationX),
      }),
    [play?.take.id],
  );
  const seekAt = (x: number) => {
    const p = session.play;
    if (!p) return;
    session.seek(Math.max(0, Math.min(1, x / Math.max(1, barW.current))) * p.take.durationS);
  };

  return (
    <ScrollView style={{ flex: 1 }} contentContainerStyle={st.content}
      showsVerticalScrollIndicator={false}>
      {play ? (
        <>
          <Card style={[st.stage, { height: stageHeight }]} padded={false}>
            <Twin style={{ flex: 1 }} />
            <View style={st.stageFoot} pointerEvents="none">
              <Label style={{ fontSize: 9.5 }}>{play.take.title}</Label>
              <Label style={{ fontSize: 9.5 }}>{play.take.id}</Label>
            </View>
          </Card>

          <Card style={st.card}>
            <View style={st.timeRow}>
              <Mono size={26} weight="500">{play.t.toFixed(2)}</Mono>
              <Mono size={13} color={C.ink3}>/ {play.take.durationS.toFixed(2)} s</Mono>
            </View>
            <View style={st.scrubWrap} {...scrub.panHandlers}
              onLayout={(e) => { barW.current = e.nativeEvent.layout.width; }}>
              <Sparkline values={trace} height={26} />
              <View style={st.scrubTrack}>
                <View style={[st.scrubFill, {
                  width: `${(play.t / Math.max(0.001, play.take.durationS)) * 100}%`,
                }]} />
              </View>
              <View style={[st.playhead, {
                left: `${(play.t / Math.max(0.001, play.take.durationS)) * 100}%`,
              }]} />
            </View>
            <View style={st.controls}>
              <Pressable onPress={() => session.togglePlay()} style={st.transport}>
                {play.playing
                  ? <View style={st.pause}><View style={st.pauseBar} /><View style={st.pauseBar} /></View>
                  : <View style={st.playTri} />}
              </Pressable>
              <View style={{ flex: 1 }} />
              <View style={{ width: 150 }}>
                <Segmented options={SPEEDS} value={speed}
                  onChange={(k) => { setSpeed(k); session.setSpeed(Number(k)); }} />
              </View>
            </View>
          </Card>

          <Pressable onPress={() => session.setTake(null)}>
            <Card style={st.exit}>
              <UIText size={14} color={C.ink2}>Close take</UIText>
            </Card>
          </Pressable>
        </>
      ) : (
        <>
          <Card style={{ padding: S.s4 }}>
            <Label>Bundled sessions</Label>
            <View style={{ height: S.s3 }} />
            {takes.map((t, i) => (
              <View key={t.id}>
                {i > 0 && <Hairline />}
                <Pressable onPress={() => session.setTake(t)} style={st.takeRow}>
                  <View style={{ flex: 1 }}>
                    <UIText size={16} weight="500">{t.title}</UIText>
                    <UIText size={12.5} color={C.ink2} style={{ marginTop: 2 }}>{t.note}</UIText>
                  </View>
                  <Mono size={12} color={C.ink3}>{t.durationS.toFixed(0)}s</Mono>
                </Pressable>
              </View>
            ))}
          </Card>
          <View style={st.note}>
            <Mono size={10.5} color={C.ink3}>Choreographed samples, not recordings of a person.</Mono>
          </View>
        </>
      )}
    </ScrollView>
  );
}

const st = StyleSheet.create({
  content: { padding: S.s4, paddingTop: S.s2, gap: S.s3, paddingBottom: S.s7 },
  stage: { overflow: 'hidden' },
  stageFoot: {
    position: 'absolute', left: S.s4, right: S.s4, bottom: S.s3,
    flexDirection: 'row', justifyContent: 'space-between',
  },
  card: { paddingVertical: S.s4 },
  timeRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginBottom: S.s3 },
  scrubWrap: { paddingVertical: S.s2 },
  scrubTrack: {
    height: 2, backgroundColor: 'rgba(23,22,20,0.10)', marginTop: 8, borderRadius: 1,
  },
  scrubFill: { height: 2, backgroundColor: C.ink, borderRadius: 1 },
  playhead: {
    position: 'absolute', bottom: 2, width: 2, height: 16,
    backgroundColor: C.accent, marginLeft: -1,
  },
  controls: { flexDirection: 'row', alignItems: 'center', marginTop: S.s4 },
  transport: {
    width: 46, height: 46, borderRadius: 23, backgroundColor: C.paperSunk,
    alignItems: 'center', justifyContent: 'center',
  },
  playTri: {
    width: 0, height: 0, marginLeft: 3,
    borderTopWidth: 8, borderBottomWidth: 8, borderLeftWidth: 13,
    borderTopColor: 'transparent', borderBottomColor: 'transparent', borderLeftColor: C.ink,
  },
  pause: { flexDirection: 'row', gap: 4 },
  pauseBar: { width: 3.5, height: 15, backgroundColor: C.ink, borderRadius: 1 },
  takeRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: S.s3, gap: S.s3 },
  exit: { paddingVertical: S.s3, alignItems: 'center' },
  note: { alignItems: 'center' },
});
