// Replay.tsx - a recorded session, played back into the same twin.
//
// The takes bundled here are the repository's own samples: choreographed and
// synthetic, generated by a script that ships beside them, using the real
// take format and the real column layout. A take recorded by the device drops
// in unchanged, which is the whole point of not inventing a format.
import React, { useMemo, useRef, useState } from 'react';
import { View, StyleSheet, Pressable, PanResponder, useWindowDimensions } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Header, Backdrop, Sheet, Row, GlassChip, BadgeButton, StageNumber, NAV_H, NAV_GAP } from '../ui/Chrome';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { T, Num, Label, Glass, IconButton, Segmented } from '../ui/primitives';
import { Trace, Sparkline } from '../ui/Meters';
import { C, S, R, FINGERS } from '../ui/tokens';
import { useSession } from '../data/session';
import { bundledTakes, type Take } from '../data/takes';

const SPEEDS = [
  { key: '0.5', label: '0.5×' }, { key: '1', label: '1×' }, { key: '2', label: '2×' },
] as const;

function effortTrace(take: Take, n = 64) {
  const step = Math.max(1, Math.floor(take.frames.length / n));
  return take.frames.filter((_, i) => i % step === 0).map((f) => Math.max(0, f.emg));
}
function peakFlexion(take: Take) {
  let m = 0;
  for (const f of take.frames) for (const k of FINGERS) m = Math.max(m, f.joints[k].mcp, f.joints[k].pip);
  return m;
}

export function Replay() {
  const session = useSession();
  return session.play ? <Transport /> : <Library />;
}

function Library() {
  const session = useSession();
  const takes = useMemo(bundledTakes, []);
  const { height } = useWindowDimensions();
  const [featured] = takes;
  const [sheet, setSheet] = useState(false);
  const inset = useSafeAreaInsets();
  return (
    <View style={{ flex: 1, backgroundColor: C.bg }}>
      <Backdrop dim={0.25} lift={0.04} scale={0.92} />
      <Header title="Replay" right={<BadgeButton icon="folder" />}
        chips={<GlassChip icon="hard-drive" label="Bundled" chevron />} />

      <View style={[st.foot, { bottom: NAV_H + NAV_GAP * 2 + inset.bottom + S.s2 }]} pointerEvents="box-none">
        <Pressable onPress={() => session.setTake(featured)}>
          <StageNumber label={featured.title} value={featured.durationS.toFixed(0)} unit="s" note={featured.note} />
        </Pressable>
        <View style={{ flexDirection: 'row', gap: S.s2 }}>
          <GlassChip icon="list" label="All takes" onPress={() => setSheet(true)} />
          <Pressable onPress={() => session.setTake(featured)} style={st.playDisc}>
            <Feather name="play" size={15} color={C.ink} style={{ marginLeft: 2 }} />
          </Pressable>
        </View>
      </View>

      <Sheet title="Sessions" open={sheet} onClose={() => setSheet(false)} share={0.6}>
        {takes.map((t, i) => (
          <Row key={t.id} label={t.title} onPress={() => session.setTake(t)} last={i === takes.length - 1}
            icon="play"
            value={<View style={{ flexDirection: 'row', alignItems: 'center', gap: S.s3 }}>
              <View style={{ width: 48, height: 18, justifyContent: 'flex-end' }}>
                <Sparkline values={effortTrace(t, 14)} n={14} height={18} recent={0} dim />
              </View>
              <Num size={14} weight="400" color={C.t2}>{t.durationS.toFixed(0)}s</Num>
            </View>} />
        ))}
        <T size={11.5} color={C.t4} style={{ textAlign: 'center', marginTop: S.s6 }}>
          Choreographed samples, not recordings of a person.
        </T>
      </Sheet>
    </View>
  );
}

function Transport() {
  const session = useSession();
  const play = session.play!;
  const { height } = useWindowDimensions();
  const [speed, setSpeed] = useState<(typeof SPEEDS)[number]['key']>(String(play.speed) as any);
  const barW = useRef(1);
  const [w, setW] = useState(0);
  const trace = useMemo(() => effortTrace(play.take, 96), [play.take.id]);
  const [sheet, setSheet] = useState(false);
  const inset = useSafeAreaInsets();
  const share = play.t / Math.max(0.001, play.take.durationS);

  const seekAt = (x: number) => {
    const p = session.play; if (!p) return;
    session.seek(Math.max(0, Math.min(1, x / Math.max(1, barW.current))) * p.take.durationS);
  };
  const scrub = useMemo(() => PanResponder.create({
    onStartShouldSetPanResponder: () => true,
    onMoveShouldSetPanResponder: () => true,
    onPanResponderGrant: (e) => seekAt(e.nativeEvent.locationX),
    onPanResponderMove: (e) => seekAt(e.nativeEvent.locationX),
  }), [play.take.id]);

  const mm = Math.floor(play.t / 60), ss = play.t - mm * 60;
  const clock = `${mm}:${ss.toFixed(1).padStart(4, '0')}`;

  return (
    <View style={{ flex: 1, backgroundColor: C.bg }}>
      <Backdrop lift={0.04} scale={0.92} />
      <Header title={play.take.title}
        left={<IconButton icon="arrow-left" size={40} onPress={() => session.setTake(null)} />}
        right={<BadgeButton icon={play.playing ? 'pause' : 'play'} onPress={() => session.togglePlay()} />}
        chips={<>
          <GlassChip icon="clock" label={`${play.take.durationS.toFixed(0)} s`} />
          <GlassChip icon="fast-forward" label={`${play.speed}×`} />
        </>} />

      <View style={[st.foot, { bottom: NAV_H + NAV_GAP * 2 + inset.bottom + S.s2 }]} pointerEvents="box-none">
        <StageNumber label={play.playing ? 'Playing' : 'Paused'} value={clock}
          note={`of ${play.take.durationS.toFixed(1)} s`} />
        <GlassChip icon="sliders" label="Transport" onPress={() => setSheet(true)} />
      </View>

      <Sheet title="Transport" open={sheet} onClose={() => setSheet(false)} share={0.6}>
        <View style={st.scrub} {...scrub.panHandlers}
          onLayout={(e) => { barW.current = e.nativeEvent.layout.width; setW(e.nativeEvent.layout.width); }}>
          <Trace values={trace} width={w} height={64} color={C.white} />
          <View style={[st.played, { width: `${share * 100}%` }]} pointerEvents="none" />
          <View style={[st.head, { left: `${share * 100}%` }]} pointerEvents="none" />
        </View>
        <View style={st.marks}>
          <Num size={11} color={C.t3}>0:00</Num>
          <Label style={{ fontSize: 10 }}>Effort</Label>
          <Num size={11} color={C.t3}>{Math.floor(play.take.durationS / 60)}:{(play.take.durationS % 60).toFixed(0).padStart(2, '0')}</Num>
        </View>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: S.s3, marginTop: S.s5 }}>
          <IconButton icon="skip-back" onPress={() => session.seek(0)} />
          <View style={{ flex: 1 }}>
            <Segmented options={SPEEDS} value={speed} onChange={(k) => { setSpeed(k); session.setSpeed(Number(k)); }} />
          </View>
          <IconButton icon="skip-forward" onPress={() => session.seek(play.take.durationS)} />
        </View>
        <View style={{ height: S.s5 }} />
        <Row icon="info" label={play.take.note} note={`${play.take.frames.length} frames · ${peakFlexion(play.take).toFixed(0)}° peak`} last />
        <T size={11.5} color={C.t4} style={{ marginTop: S.s4, lineHeight: 16 }}>
          Sample takes write anatomical abduction into the MCP column; the twin clamps it at 16°.
        </T>
      </Sheet>
    </View>
  );
}

const st = StyleSheet.create({
  foot: { position: 'absolute', left: S.s5, right: S.s5, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  playDisc: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center' },
  scrub: { marginTop: S.s2, height: 64 },
  played: { position: 'absolute', left: 0, top: 0, bottom: 0, backgroundColor: 'rgba(255,91,46,0.18)', borderRadius: 4 },
  head: { position: 'absolute', top: -4, bottom: -4, width: 2, backgroundColor: C.accent, marginLeft: -1 },
  marks: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
});
